### ISSUE TITLE
RPC move command

### ISSUE THREAD

**Issue by Crypto2** [transferdev/Transfercoin#36]
Your RPC move command is broken, if used it corrupts the wallet balances so you have to salvage the wallet.

In rpcwallet.cpp on the movecmd() function you can see it adds the debit accounting entry 2x instead of the credit entry. Easy fix at least.

**Comment by gentamicin** [comment]
perhaps my proposed fixes to rpcrawtransaction.cpp will fix this

**Comment by Infernoman** [comment]
Fixed !
