### ISSUE TITLE
cannot compile transfercoin, any advice on compiling secp256k1 ?

### ISSUE THREAD

**Issue by gentamicin** [transferdev/Transfercoin#38]
/home/gentamicin/Transfercoin/src/key.cpp:216: undefined reference to `secp256k1_ecdsa_sign_recoverable'
/home/gentamicin/Transfercoin/src/key.cpp:218: undefined reference to`secp256k1_ecdsa_recoverable_signature_serialize_compact'
obj/pubkey.o: In function `CPubKey::RecoverCompact(uint256 const&, std::vector<unsigned char, std::allocator<unsigned char> > const&)':
/home/gentamicin/Transfercoin/src/pubkey.cpp:194: undefined reference to`secp256k1_ecdsa_recoverable_signature_parse_compact'
/home/gentamicin/Transfercoin/src/pubkey.cpp:197: undefined reference to `secp256k1_ecdsa_recover'

**Comment by joshafest** [comment]
same here

**Comment by bumbacoin** [comment]
when building secp256k1 try using 

./autogen.sh
./configure --enable-module-recovery
make

**Comment by Infernoman** [comment]
Secp256k1 should auto compile by itself now when compiling on Linux or mac. And Secp256k1 is pre packaged and compiled with the windows build environment.
