### ISSUE TITLE
Unable to sync on MacOS

### ISSUE THREAD

**Issue by damianobarbati** [transferdev/Transfercoin#59]
On MacOS High Sierra the wallet doesn't seem to sync at all.
I imported the blockchain downloaded from the website.
As you can see in the screens there's no traffic at all and `0 active connection(s) to Transfer network`: do I need to add nodes manually? 
<img width="725" alt="schermata 2017-12-14 alle 20 28 49" src="https://user-images.githubusercontent.com/2225869/34010668-df41311c-e10d-11e7-9106-10d18dc63083.png">
<img width="728" alt="schermata 2017-12-14 alle 20 28 44" src="https://user-images.githubusercontent.com/2225869/34010669-df6e2528-e10d-11e7-9b4e-66238c557598.png">
<img width="1440" alt="schermata 2017-12-14 alle 20 29 11" src="https://user-images.githubusercontent.com/2225869/34010670-df997bd8-e10d-11e7-9e3c-26dd937320cf.png">

**Comment by Infernoman** [comment]
The dns nodes have been restored to there working order so this issue should be resolved. Please advise if the issue persists.
